name: "Feature Request"
description: "Suggest a new feature for the website or API"
title: "Feature Request: "
labels: enhancement
body:
  - type: checkboxes
    id: type
    attributes:
      label: Request Type
      description: "Select the type of feature request:"
      options:
        - label: "Website Feature"
        - label: "API Enhancement"

  - type: textarea
    attributes:
      label: Feature Description
      description: |
        Please provide a detailed description of the feature you're requesting.
        For website features, include how the feature would improve user experience.
        For API enhancements, describe the functionality you'd like to see added.
      placeholder: |
        Example:
        - Website: A dark mode option to reduce eye strain.
        - API: Add support for querying user statistics.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: |
        Explain how this feature would be useful to you or others.
        For website features, discuss scenarios where this feature would be beneficial.
        For API enhancements, describe the potential applications.
      placeholder: |
        Use case examples...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional context that might help us understand the feature better.
      placeholder: |
        Additional information...
