name: "Feature Request"
description: "Suggest a new feature for SkinBook"
title: "Feature Request: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: |
        Please provide a detailed description of the feature you're requesting.
      placeholder: |
        A feature I'd like to see is...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional context that might help us understand the feature better.
      placeholder: |
        Additional information...
