name: "Issue Report"
description: "Report an issue about SkinBook"
title: "Issue Report: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the Issue
      description: |
        Please provide a clear and concise description of the issue you're facing.
      placeholder: |
        This issue I'm running into...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide information about your environment.
        For website issues, include your browser and operating system.
        For API issues, include your programming language and version.
      placeholder: |
        Example:
        - Browser: Chrome 91.0.4472.124
        - OS: Windows 10
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional context that might help us understand the issue better.
      placeholder: |
        Additional information...
